version: 2.1

commands:
  install_npm_deps:
    description: Install deps from NPM
    steps:
      - run:
          name: Install pnpm
          command: |
            sudo npm install -g pnpm@7.9.5
            pnpm config set store-dir /home/circleci/.pnpm-store
      - run:
          name: Install deps
          command: pnpm install --frozen-lockfile

  checkout_a11y:
    description: Checkout the git repo with a standard root
    steps:
      - checkout:
          path: /home/circleci/solid-a11y

executors:
  awscli:
    docker:
      - image: dairyisscary/awscli:1.22.58
    resource_class: small

  default_node:
    docker:
      - image: cimg/node:16.13.2
    resource_class: small
    working_directory: /home/circleci/solid-a11y

  terraform:
    docker:
      - image: dairyisscary/terraform:1.1.7
    resource_class: small
    working_directory: /home/circleci/solid-a11y/infra

jobs:
  build_npm_package:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Build
          command: |
            pnpm --filter solid-a11y clean
            pnpm --filter solid-a11y build
      - persist_to_workspace:
          root: "./"
          paths:
            - packages/solid-a11y/dist
            - packages/solid-a11y/types

  build_static_documentation:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Build Docs Static Content
          command: pnpm --filter solid-a11y-docs build
      - persist_to_workspace:
          root: "./"
          paths:
            - packages/solid-a11y-docs/dist

  deploy_documentation:
    executor: awscli
    working_directory: /home/circleci/solid-a11y/packages/solid-a11y-docs
    steps:
      - checkout_a11y
      - attach_workspace:
          at: /home/circleci/solid-a11y
      - run:
          name: Upload Static Assets
          command: |
            ONE_YEAR="31536000"
            BROWSER_EXPIRES="public, max-age=0, s-maxage=$ONE_YEAR, must-revalidate"
            BROWSER_IMMUTABLE="public, max-age=$ONE_YEAR, immutable"
            BUCKET_NAME="$(cat ../../infra/output/terraform.json | jq '.documentation_static_bucket_name.value' -r)"

            aws s3 cp --metadata-directive REPLACE --content-type "text/html; charset=utf-8" --cache-control "$BROWSER_EXPIRES" dist/*.html "s3://$BUCKET_NAME"

            aws s3 cp --recursive --metadata-directive REPLACE --cache-control "$BROWSER_IMMUTABLE" dist/assets "s3://$BUCKET_NAME/assets"

  format:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Check Base Formatting
          command: pnpm exec prettier --check .

  format_infrastructure_configuration:
    executor: terraform
    working_directory: /home/circleci/solid-a11y
    steps:
      - checkout_a11y
      - run:
          name: Check Infrastructure Formatting
          command: terraform fmt -check -diff -list=true -recursive

  lint:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Lint
          command: pnpm exec eslint --ext .js,.cjs,.ts,.tsx --max-warnings 0 .
          environment:
            USE_EXPENSIVE_LINT_RULES: yes

  provision_infrastructure:
    executor: terraform
    steps:
      - checkout_a11y
      - run:
          name: Init Terraform
          command: terraform init
      - run:
          name: Form and Provision Infrastructure
          command: |
            mkdir -p output
            terraform apply -auto-approve
            terraform output -json > output/terraform.json
      - persist_to_workspace:
          root: "../"
          paths:
            - infra/output

  publish_npm_package:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - attach_workspace:
          at: /home/circleci/solid-a11y
      - run:
          name: Publish
          command: pnpm publish --access public --filter solid-a11y --publish-branch production-npm

  test:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Run Tests
          command: pnpm -r --no-bail test -- run
          environment:
            VITEST_MAX_THREADS: 2
            VITEST_MIN_THREADS: 2

  typecheck:
    executor: default_node
    steps:
      - checkout_a11y
      - install_npm_deps
      - run:
          name: Typecheck
          command: pnpm -r --no-bail exec tsc

  validate_infrastructure_configuration:
    executor: terraform
    steps:
      - checkout_a11y
      - run:
          name: Init Terraform
          command: terraform init -backend=false
      - run:
          name: Validate Infrastructure
          command: terraform validate

workflows:
  version: 2
  "Check and Deploy":
    jobs:
      - build_npm_package:
          filters:
            branches:
              ignore: production-docs
      - build_static_documentation:
          filters:
            branches:
              ignore: production-npm
      - deploy_documentation:
          filters:
            branches:
              only: production-docs
          requires:
            - provision_infrastructure
            - build_static_documentation
      - format
      - format_infrastructure_configuration
      - lint
      - provision_infrastructure:
          filters:
            branches:
              only: production-docs
          requires:
            - validate_infrastructure_configuration
      - publish_npm_package:
          filters:
            branches:
              only: production-npm
          requires:
            - build_npm_package
            - format
            - lint
            - test
            - typecheck
      - test
      - typecheck
      - validate_infrastructure_configuration
